# Generated by Django 4.2 on 2023-04-28 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddVendors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendorname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='AddProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('product_holesale_price', models.IntegerField()),
                ('product_retail_price', models.IntegerField()),
                ('product_customer_price', models.IntegerField()),
                ('product_category', models.CharField(max_length=30)),
                ('product_image', models.ImageField(upload_to='product_images')),
                ('vendorname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gridfokuzapp.addvendors')),
            ],
        ),
    ]
