# Generated by Django 4.2 on 2023-04-29 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridfokuzapp', '0002_rename_vendorname_addproducts_vendor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproducts',
            name='product_image',
            field=models.ImageField(null=True, upload_to='product_images'),
        ),
    ]
