# Generated by Django 4.2 on 2023-05-04 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gridfokuzapp', '0005_manualcombo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ManualCombo',
            new_name='ManualComboTemp',
        ),
    ]
