# Generated by Django 4.2 on 2023-05-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridfokuzapp', '0008_alter_manualcombotemp_product_pdftemp'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdftemp',
            name='grand_total',
            field=models.FloatField(null=True),
        ),
    ]
