# Generated by Django 4.2 on 2023-06-06 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridfokuzapp', '0009_pdftemp_grand_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='addvendors',
            name='ventorcode',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
