# Generated by Django 4.2 on 2023-06-11 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridfokuzapp', '0010_addvendors_ventorcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproducts',
            name='discription',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
