# Generated by Django 4.2 on 2023-06-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridfokuzapp', '0013_addproducts_temp_discription'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproducts',
            name='final_price',
            field=models.FloatField(null=True),
        ),
    ]
