# Generated by Django 4.2 on 2023-06-25 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gridfokuzapp', '0014_addproducts_final_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addproducts',
            old_name='Branding',
            new_name='branding_cost',
        ),
        migrations.RenameField(
            model_name='addproducts',
            old_name='GF_Price',
            new_name='profit_percentage',
        ),
        migrations.RenameField(
            model_name='addproducts',
            old_name='Packing',
            new_name='tax',
        ),
        migrations.RenameField(
            model_name='addproducts',
            old_name='Profit_amount',
            new_name='transportation_cost',
        ),
        migrations.RemoveField(
            model_name='addproducts',
            name='Profit_in_precentage',
        ),
        migrations.RemoveField(
            model_name='addproducts',
            name='Tax_amount',
        ),
        migrations.RemoveField(
            model_name='addproducts',
            name='Tax_in_precentage',
        ),
        migrations.RemoveField(
            model_name='addproducts',
            name='Transport1',
        ),
        migrations.RemoveField(
            model_name='addproducts',
            name='Transport2',
        ),
        migrations.RemoveField(
            model_name='addproducts',
            name='product_image2',
        ),
        migrations.RemoveField(
            model_name='addproducts',
            name='product_image3',
        ),
    ]
