# Generated by Django 4.2 on 2023-06-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridfokuzapp', '0015_rename_branding_addproducts_branding_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproducts',
            name='branding_category',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
