# Generated by Django 4.2 on 2023-06-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridfokuzapp', '0016_addproducts_branding_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproducts',
            name='branding_cost',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='addproducts',
            name='profit_percentage',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='addproducts',
            name='transportation_cost',
            field=models.FloatField(default=0, null=True),
        ),
    ]
