# Generated by Django 4.2 on 2023-07-13 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gridfokuzapp', '0020_tempfilter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TempFilter',
        ),
    ]
