# Generated by Django 4.2 on 2023-07-24 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gridfokuzapp', '0022_logos_alter_logo_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logos',
        ),
    ]
