# Generated by Django 4.2 on 2023-08-08 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridfokuzapp', '0023_delete_logos'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproducts',
            name='usrinput',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
